---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-figs/"
)
```

# ggaqua

Contains a simple theme for ggplot2, `theme_aqua()`, that is based on SLU Aqua report style. The theme builds on `ggplot2::theme_bw()`. 

Installing:

```{r, eval=FALSE}
# install.packages("devtools")
devtools::install_github("maxlindmark/ggaqua")

# slu aqua colors
if (!require(remotes)) {
install.packages(remotes)
}
remotes::install_github("kagervall/SLUcolors")
```

Below is an example plot of a time series of catch of Pike in the large lakes in Sweden (a dataset that is built in here called "pike").

```{r, echo=FALSE}
set.seed(1)
```

```{r example, fig.width=5.5, fig.height=3.6, fig.retina=2}
library(ggplot2)
library(ggaqua)
library(SLUcolors)

pal <- SLUpalette(1)

# a basic slu-aqua themed plot
ggplot(pike, aes(Year, Response_variable)) + 
  geom_bar(stat = "identity", width = 0.6, fill = pal[1]) +
  scale_x_continuous(expand = c(0, 0), breaks = scales::pretty_breaks(n = 6)) +
  scale_y_continuous(expand = c(0, 0), breaks = scales::pretty_breaks(n = 5)) +
  theme_aqua() + 
  labs(y = "Landningar (ton)")
```
